# Generated by Django 3.2.5 on 2021-09-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=123)),
                ('last_name', models.CharField(max_length=123)),
                ('username', models.CharField(max_length=123)),
                ('email', models.EmailField(max_length=123)),
                ('password1', models.CharField(max_length=123)),
                ('password2', models.CharField(max_length=123)),
            ],
        ),
    ]
