# Generated by Django 3.2.5 on 2021-09-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='username',
        ),
    ]
