# Generated by Django 3.2.5 on 2021-09-01 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_reg_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='Username',
            field=models.CharField(default=django.utils.timezone.now, max_length=198),
            preserve_default=False,
        ),
    ]
