# Generated by Django 3.2.5 on 2021-09-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210901_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Pwd', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
