# Generated by Django 3.2.5 on 2021-09-04 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210904_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='Username',
        ),
        migrations.AddField(
            model_name='newuser',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
